### ISSUE TITLE
Add option for Listen function in app.js for cloud9

### ISSUE THREAD

**Issue by keertirajmalik** [WebDevelopementProject/Matching-Animal#3]
add  another app.listen function which will be used for cloud9 configuration

`app.listen(){

}`

and comment out the one of the 2 function

**Comment by DevDavidUser** [comment]
Done by @Elemento24 
var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);
